### ISSUE TITLE
Erro ao importar ao importar o módulo do FGAme

### ISSUE THREAD

**Issue by felipe72** [fabiommendes/FGAme#20]
### Comportamento esperado

Ser capaz de importar o módulo após instalá-lo

### Comportamento atual
Ao importar o módulo, ele dá o seguinte erro:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/FGAme/__init__.py", line 3, in <module>
    from .asset import Asset
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/FGAme/asset.py", line 6, in <module>
    from FGAme.utils import snake_case
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/FGAme/utils/__init__.py", line 4, in <module>
    from smallshapes.utils import accept_vec_args
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/smallshapes/__init__.py", line 2, in <module>
    from .core import *
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/smallshapes/core/__init__.py", line 1, in <module>
    from .base import SmallshapesBase, MathFunctionsMixin
  File "/home/felipe/fgam/fgame/lib/python3.5/site-packages/smallshapes/core/base.py", line 1, in <module>
    from smallvectors import Flatable, MathFunctionsMixin as _MathFunctionsMixin, \
ImportError: cannot import name 'Flatable'
```

O erro acima foi gerado utilizando o python3.5. Utilizando o python2, o erro gerado é durante a instalação do pacote, utilizando o pip2.

```
Collecting smallshapes>=0.6.2 (from fgame)
  Downloading https://files.pythonhosted.org/packages/b6/69/a0d5c11d3331b6ee6597f41917cc22b435c60ee8b4b470c4c37f60f3c0c2/smallshapes-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kNaCML/smallshapes/setup.py", line 25, in <module>
        with open(file_name, 'w', encoding='utf-8') as F:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kNaCML/smallshapes/
```

O erro acima provavelmente é devido à uma nova atualização do módulo ```smallshapes```. E uma possível solução é a limitação de uma versão antiga para esse repositório.

#### Para o erro 1
- Passo 1: Instalar o módulo utilizando o pip
- Passo 2: Importar o módulo em um código python

#### Para o erro 2
- Passo 1: Apenas instalar o módulo utilizando o pip2

**Comment by felipe72** [comment]
@RochaCarla
